openapi: 3.0.0
info:
  description: "Oauth 2.0 Authorization Server"
  version: "1.0.0"
  title: "Authorization Server"
  termsOfService: "https://swagger.io/terms/"
  contact:
    email: "jimmy.vn.contractor@gmail.com"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "http://localhost:3000"
    description: Local Environment
  - url: "https://oauth.gotcloud.app"
    description: PROD Environment
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/v1/ping:
    get:
      tags:
        - Ping
      description: Returns API operational status
      responses:
        '200':
          description: OK
  /oauth/authorize:
    get:
      tags:
        - OAuth Flows
      description: Authorize client
      parameters:
        - name: client_id
          in: query
          description: ID of the client
          required: true
        - name: response_type
          in: query
          description: Response type of authorization, types are supported [code]
          required: true
      responses:
        '200':
          description: Authorized
        '404':
          description: Client not found in the system
        '400':
          description: Bad Request, missing params
  /oauth/token:
    post:
      tags:
        - OAuth Flows
      description: Get Token and related information.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - client_id
                - client_secret
                - grant_type
                - code
                - redirect_uri
              properties:
                client_id:
                  type: string
                  description: Client ID
                client_secret:
                  type: string
                  description: Client secret
                grant_type:
                  type: string
                  description: Grant Type
                code:
                  type: string
                  description: Authorization Code
                redirect_uri:
                  type: string
                  description: Client Redirect URL (Callback URL)
      responses:
        '200':
          description: Successfully
        '404':
          description: Client not found in the system
        '400':
          description: Bad Request, missing body content
        '503':
          description: Error Service Unavailable
  /oauth/token/refresh:
    post:
      tags:
        - OAuth Flows
      description: Refresh Token.
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - grant_type
                - refresh_token
              properties:
                grant_type:
                  type: string
                  description: Grant Type [refresh_token]
                refresh_token:
                  type: string
                  description: Refresh Token value
      responses:
        '200':
          description: Successfully
        '404':
          description: Client not found in the system
        '400':
          description: Bad Request, missing Basic Auth or body content
        '503':
          description: Error Service Unavailable
  /api/v1/protected-test:
    get:
      tags:
        - Retrieve data after authentication
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Authorized
        '404':
          description: Client not found in the system
        '400':
          description: Bad Request, missing Basic Auth or body content
        '503':
          description: Error Service Unavailable